// <auto-generated />
namespace Ideky.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Let_Picture_Be_Null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Let_Picture_Be_Null));
        
        string IMigrationMetadata.Id
        {
            get { return "201707120059238_Let_Picture_Be_Null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
