// <auto-generated />
namespace Ideky.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatemappingusernamelength200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemappingusernamelength200));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111926453_update-mapping-user-name-length-200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
