// <auto-generated />
namespace Ideky.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Createnameandpictureinuserentityandupdateothersmethods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createnameandpictureinuserentityandupdateothersmethods));
        
        string IMigrationMetadata.Id
        {
            get { return "201707102059489_Create-name-and-picture-in-user-entity-and-update-others-methods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
